<a href="https://colab.research.google.com/github/Luis-Eduardo-P-Ch/Programacion-para-el-Analisis-de-datos/blob/main/Practica3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programación para Análisis de datos
## Práctica 3: Numpy



<b>Nota:</b>
Esta practica esta basada en los ejercicios presentes en https://github.com/rougier/numpy-100.

numpy-100: Version 1.1
Nicolas P. Rougier; Jessica B. Hamrick; ibah; Gavin Heverly-Coulson; Dapid; Christoph Deil; Bartosz Telenczuk

<hr>

#### 1. Import the numpy package under the name `np`

In [ ]:
pip install 

ERROR: You must give at least one requirement to install (see "pip help install")


In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


La diferencia entre "pip install" y "!pip install" radica en el entorno de ejecución en el que se ejecutan estos comandos.

"pip install" es un comando que se utiliza para instalar paquetes de Python en un entorno de Python. Puede ser utilizado dentro de una sesión interactiva de Python o dentro de un archivo de script de Python.

Por otro lado, "!pip install" es un comando que se utiliza dentro de un notebook de Jupyter o en un entorno de ejecución como Colab. El signo de exclamación ("!") es una sintaxis especial que indica que el comando debe ser ejecutado en una terminal o shell en lugar de en el entorno de Python. Esto permite ejecutar comandos de sistema en el notebook o en el entorno de ejecución.

En resumen, "pip install" es un comando de Python que se ejecuta en un entorno de Python, mientras que "!pip install" es un comando que se ejecuta en una terminal o shell en un notebook de Jupyter o entorno de ejecución como Colab.

No, no es lo mismo usar "!pip install" que "import".

"!pip install" es un comando que se utiliza para instalar paquetes de Python en un entorno de ejecución como Colab. Este comando solo se usa una vez para instalar el paquete que se desea utilizar. Por otro lado, "import" es un comando de Python que se utiliza para importar un paquete o módulo que ya está instalado en el entorno de Python.

En resumen, "!pip install" se utiliza para instalar un paquete en el entorno de ejecución, mientras que "import" se utiliza para importar un paquete o módulo que ya está instalado en el entorno de Python y se puede utilizar para trabajar con ese paquete o módulo en el código Python.

Por lo tanto, necesitas usar "!pip install" para instalar un paquete en Colab antes de poder importarlo y usarlo en tu código con el comando "import".

#### 2. Print the numpy version and the configuration

In [ ]:
import numpy as np

print("Versión de NumPy: ", np.__version__)

Versión de NumPy:  1.22.4


#### 3. Create a null vector of size 10

In [ ]:
import numpy as np

vector_nulo=np.zeros(10)

print(vector_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array

In [ ]:
import numpy as np

#Crear un array de ejemplo
array_ejemplo=np.zeros((3,4))

#Encontrar el tamaño de memoria del array
tamaño_memoria=array_ejemplo.nbytes

#Imprimir el tamaño de memoria del array en bytes
print("El tamañ de memoria del array es: ", tamaño_memoria, "bytes")

El tamañ de memoria del array es:  96 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [ ]:
import numpy as pd

help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
import numpy as np
#Crear un vector nulo de tamaño 10
vector=np.zeros(10)

#asignar el valor de 1 en la quinta posición
vector[4]=1

#Imprimir el vector resultante
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
#crear una matriz identidad de tamaño 10*10
matrix=np.eye(10)

#Selecionar la quinta columna de la matriz identidad
vector=matrix[:,4]

#imprimir el vector resultante

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [ ]:
import numpy as np

#Crear un vector con Valores que van desde 10 a 49
vector=np.arange(10, 50)

#Imprimir el vector resultante
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last)

In [ ]:
import numpy as np

#Crear un vector de ejemplo

vector=np.array([1, 2, 3, 4, 5])

#Invertir el vector utilizando la notación de índices
vector_invertido= vector[::-1]

#Imprimiir el vector resultante
print(vector_invertido)

[5 4 3 2 1]


In [ ]:
import numpy as np

#Crear un Vector de ejemplo
vector=np.array([1, 2, 3, 4, 5])

#Invertir el vector utilizando la notación de Indices y asignar al vector original
vector[:]= vector[::-1]

#Imprimir el vector resultante
print(vector)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
#Crear un arreglo Numpy de 3*3 con ceros
matriz=np.zeros((3,3))

#Generar una secuencia de números de 0 a 8
valores=np.arange(0,9)

#Darle forma de 3*3 al arreglo de valores
valores= valores.reshape((3, 3))


#Asignar los valores a la matriz
matriz= valores

print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
lista=[1, 2, 0, 0, 4, 0]
indices=[]

#Recorrer la lista y comprobar si cada elemento es distinto de cero

for i in range(len(lista)):
  if lista[i] !=0:
    indices.append(i)
print(indices)

[0, 1, 4]


#### 11. Create a 3x3 identity matrix

In [ ]:
import numpy as np

# Crear na matriz identidad de 3*3
matriz_identidad=np.identity(3)

print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [ ]:
import numpy as np

#Crear una matriz de 3*3*3 con valores aleatorios

matriz_aleatoria=np.random.rand(3, 3, 3)

print(matriz_aleatoria)

[[[6.34922896e-01 5.68116134e-01 7.75763385e-01]
  [5.93665162e-01 9.02457849e-01 7.83259379e-01]
  [7.49998201e-04 4.05427207e-01 5.86584467e-01]]

 [[4.32177363e-01 4.02547871e-01 3.94583945e-01]
  [4.33147314e-01 2.11310756e-01 5.99640455e-01]
  [7.72952005e-01 6.67541440e-02 7.69456121e-01]]

 [[7.75637048e-01 5.89431926e-01 6.63039162e-01]
  [8.18808858e-01 5.07534334e-01 1.65621650e-01]
  [1.76254061e-01 6.92020339e-01 1.94579147e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
import numpy as np

# Crear una matriz de 10*10 con valores aleatorios
matriz_aleatoria=np.random.rand(10,10)

#Encontrar el valor minimo y el valor máximo de la matriz
valor_minimo=np.min(matriz_aleatoria)
valor_maximo= np.max(matriz_aleatoria)

print("matriz aleatoria:")
print(matriz_aleatoria)
print("Valor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)

matriz aleatoria:
[[0.56476361 0.31852391 0.93268225 0.80361594 0.2056231  0.71242543
  0.98981644 0.32044578 0.47124292 0.99646601]
 [0.83038285 0.22718839 0.3041835  0.24371791 0.05681253 0.73362443
  0.76565586 0.30431667 0.6594878  0.04946378]
 [0.55085225 0.62886716 0.84584389 0.84577677 0.59517093 0.64598479
  0.03434006 0.36045763 0.74074011 0.20134802]
 [0.5240747  0.02463128 0.0107314  0.30079198 0.46439479 0.8976309
  0.95986099 0.93353059 0.21643233 0.88520224]
 [0.5036528  0.89171279 0.5514514  0.4698113  0.28853872 0.69443916
  0.7516785  0.84515178 0.61314978 0.35342786]
 [0.32710684 0.10744226 0.69824899 0.92792237 0.82083552 0.93481095
  0.46190438 0.39077299 0.97150381 0.63662744]
 [0.86073556 0.17610446 0.63347564 0.06611302 0.79416864 0.32847135
  0.89844417 0.88195308 0.27265855 0.7405223 ]
 [0.61794636 0.24083674 0.63301943 0.58089528 0.4384992  0.22673392
  0.47454204 0.36090496 0.18496788 0.657466  ]
 [0.01809534 0.04412209 0.96964818 0.78695143 0.14106067 0.5449

#### 14. Create a random vector of size 30 and find the mean value

In [ ]:
import numpy as np

#Crear un vector de 30 valores aleatoios
vector_aleatorio=np.random.rand(1,30)

#Encontrar el valor medio del vector
valor_medio=np.mean(vector_aleatorio)

print("Vector aleatorio:")
print(vector_aleatorio)
print("valor medio: ", valor_medio)


Vector aleatorio:
[[0.57291188 0.82050745 0.72821455 0.85307017 0.8479507  0.93871675
  0.85326141 0.52177569 0.97098906 0.21054297 0.44594836 0.84135229
  0.14678619 0.35461587 0.64497202 0.49042242 0.17278906 0.66013596
  0.24551298 0.39509084 0.81722908 0.40896539 0.45495039 0.62240089
  0.96371009 0.54607743 0.58147109 0.19290633 0.89735553 0.40579344]]
valor medio:  0.5868808775510813


#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
import numpy as np

#Definir las dimensiones de la matriz
filas=5
columnas=5

# Crear una matriz llena de ceros
matriz=np.zeros((filas, columnas))

#Establecer los bordes con unos
matriz[0, :]=1
matriz[filas-1,:]=1   #ultima fila
matriz[:, 0]=1
matriz[:, columnas-1]=1

#imprimir la matriz resultante
print(matriz)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
import numpy as np

# Definir la matriz original
matriz_original=np.array([[1, 2, 3], [4, 5, 6], [ 7, 8, 9]])

# Agregar un borde lleno de ceros alrededor de la matriz
matriz_con_borde= np.pad(matriz_original, 1, mode='constant', constant_values=0)

print(matriz_con_borde)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan   # nan
np.nan == np.nan   # False (nan no es igual a ningún valor, ni siquiera a otro nan)
np.inf > np.nan   # False (cualquier número, incluso infinito, no puede ser mayor que nan)
np.nan - np.nan   # nan (restar dos valores indefinidos da como resultado indefinido)
np.nan in set([np.nan])   # True (un conjunto puede contener valores indefinidos)
0.3 == 3 * 0.1   # False (debido a errores de redondeo en la representación de números de punto flotante)

False

En resumen, la expresión arrojaría valores indefinidos (nan) y falsos debido a la naturaleza indefinida de los números no definidos. Además, debido a errores de redondeo en la representación de números de punto flotante, la igualdad entre 0.3 y 3 * 0.1 también arrojaría un resultado falso.

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
import numpy as np

#Crear matriz de ceros de 5*5
matriz=np.zeros((5, 5))

#Establecer los valores debajo de la diagonal en 1, 2, 3, 4
for i in range(1, 5):
  matriz[i:(i+1), 0:i]=i
#Imprimir la matriz resultante
print(matriz)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 2. 0. 0. 0.]
 [3. 3. 3. 0. 0.]
 [4. 4. 4. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
import numpy as np

#Crear una matriz de 8*8 llena de ceros
matriz= np.zeros((8, 8))

#Rellenar la matriz con el patron de ajedrez utilizando el operador módulo

for i in range(8):
  for j in range(8):
    if (i+j)%2==0:
      matriz[i][j]=1
#imprimir la matriz resultante
print(matriz)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
import numpy as mp

#Crear una matriz de forma (6, 7, 8) con valores aleatorios
matriz=np.random.rand(6, 7, 8)

# Encontrar el indice(x, y, z) del elemento numero 100

indice= np.unravel_index(100, matriz.shape)
#imprimir el indice resultante

print(indice)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
import numpy as np

#matriz de colores de las casillas negras
black= np.zeros([4, 4])

black[1::2,::2]=1    # [1::2, es la fila 1 pasado una fila poner =1 ; la otra parte del corchete ::2] quiere decir desde la coluna 0 pasado una columna poner 1.
black[::2, 1::2]=1  # En este caso desde la fila 0 pasando 1 fila y desde la columna 1 pasando una columna poner=1

# matriz de colores de las casillas blancas
white= np.ones([4, 4])
white[1::2, ::2]=0
white[::2, 1::2]=0

#Utilice la función de mosaico de Numpy para crear una matriz de 8*8

board= np.tile(np.block([[white, black], [black, white]]), (4,4))

print(board)


[[1. 0. 1. ... 1. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [1. 0. 1. ... 1. 0. 1.]
 ...
 [1. 0. 1. ... 1. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [1. 0. 1. ... 1. 0. 1.]]


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


#### 22. Normalize a 5x5 random matrix

In [ ]:
import numpy as np

matriz_aleatoria= np.random.rand(5,5)

#Calcule la media y la desviación estándar de la matriz utilizando las 
#funciones "np.mean()" y "np.std()" de NumPy.

media=np.mean(matriz_aleatoria)
desviacion_estandar= np.std(matriz_aleatoria)

#Normalizar la matriz restando la media y dividiendo por la desviación estandar

matriz_normalizada= (matriz_aleatoria - media) / desviacion_estandar

print(matriz_normalizada)

[[-0.33616017 -0.36513149 -0.36620737  0.6712382   1.63625594]
 [-1.00271466 -0.99829986 -0.14421699 -1.31352934  1.55769246]
 [-1.34094371 -0.14468261  1.35161194  1.51462178  0.80550455]
 [-1.3666614  -0.26184334  1.22979889 -0.39252852 -1.24813036]
 [ 1.0500024   0.05347889 -1.3882817   0.07123081  0.72789566]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [1]:
import numpy as np

# Crear un dtype personalizado para un color
color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

# Crear un array de colores utilizando el dtype personalizado
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

# Imprimir el array de colores
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [2]:
import numpy as np

# Crear la primera matriz de 5x3
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])

# Crear la segunda matriz de 3x2
matriz2 = np.array([[1, 2], [3, 4], [5, 6]])

# Multiplicar las dos matrices utilizando numpy.dot()
resultado = np.dot(matriz1, matriz2)

# Imprimir el resultado
print(resultado)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [3]:
import numpy as np

# Crear una matriz de 1 dimensión
matriz = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negar los elementos que están entre 3 y 8
matriz_nueva = np.where((matriz >= 3) & (matriz <= 8), -matriz, matriz)

# Imprimir la matriz resultante
print(matriz_nueva)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#La salida del siguiente script es 9. La primera línea de código utiliza la función sum() 
#para sumar los elementos de un rango de números del 0 al 4, y se le resta -1. 
#El rango de números del 0 al 4 es [0, 1, 2, 3, 4], y la suma de estos números es 10. 
#Al restar -1, el resultado final es 9. La segunda línea de código importa la biblioteca 
#NumPy y utiliza la función sum() para sumar los elementos de un rango de números del 0 al 4,
# y se le resta -1. Sin embargo, la sintaxis de la función sum() en NumPy es diferente a la
# función sum() de Python. En NumPy, el primer argumento de la función sum() es el array que 
#se quiere sumar, y el segundo argumento es el eje a lo largo del cual se quiere sumar. 
#En este caso, el segundo argumento es -1, lo que significa que se quiere sumar a lo largo 
#del último eje. Como el rango de números del 0 al 4 es un array de 1 dimensión, el último 
#eje es el único eje, y la suma de los elementos es 10. Al restar -1, el resultado final es 11.



9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#La única expresión legal en Python es z**z. Esta expresión eleva cada elemento del vector `z` a la potencia de sí mismo. Las otras expresiones no son legales en Python y arrojarán errores de sintaxis o de tipo.
#• 2 << z >> 2 es una expresión ilegal porque no se puede realizar un desplazamiento a la izquierda y a la derecha con dos operandos. Se debe especificar la cantidad de bits a desplazar.
#• z <- z es una expresión ilegal porque el operador < no se puede utilizar con dos operandos del mismo tipo.
#• 1j*z es una expresión ilegal porque el operador * no se puede utilizar con un número complejo y un vector entero.
#• z/1/1 es una expresión ilegal porque no se puede dividir un vector entero por un número entero.
#• z<z>z es una expresión ilegal porque el operador < no se puede utilizar con dos operandos del mismo tipo.

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [6]:
np.array(0) / np.array(0)

np.array(0) // np.array(0)

#La expresión np.array(0) / np.array(0) devuelve nan (Not a Number) en NumPy. Esto se debe a que la división por cero no está definida y NumPy devuelve nan en lugar de arrojar un error.
#La expresión np.array(0) // np.array(0) devuelve un error de división por cero. En Python, la división entera por cero no está definida y arroja un error.

<ipython-input-6-19d0e8decd47>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-6-19d0e8decd47>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [5]:
np.array([np.nan]).astype(int).astype(float)

#La expresión np.array([np.nan]).astype(int).astype(float) devuelve array([-9.22337204e+18]). 
#Primero, se convierte el valor `nan` a un entero utilizando la función astype(int), lo que devuelve -922337204. 
#Luego, se convierte este entero a un flotante utilizando la función astype(float), lo que devuelve -9.22337204e+18.


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ?

#### 30. How to find common values between two arrays?

#### 31. How to ignore all numpy warnings (not recommended)?

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow?

#### 34. How to get all the dates corresponding to the month of July 2016? 

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

#### 36. Extract the integer part of a random array using 5 different methods 

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 

#### 38. Consider a generator function that generates 10 integers and use it to build an array

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

#### 40. Create a random vector of size 10 and sort it 

#### 41. How to sum a small array faster than np.sum? 

#### 42. Consider two random array A and B, check if they are equal 

#### 43. Make an array immutable (read-only) 

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

#### 45. Create random vector of size 10 and replace the maximum value by 0 

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area 

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type 

#### 49. How to print all the values of an array? 

#### 50. How to find the closest value (to a given scalar) in a vector? 

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) 

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? 
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? 

#### 56. Generate a generic 2D Gaussian-like array 

#### 57. How to randomly place p elements in a 2D array? 

#### 58. Subtract the mean of each row of a matrix 

#### 59. How to sort an array by the nth column? 

#### 60. How to tell if a given 2D array has null columns? 

#### 61. Find the nearest value from a given value in an array 

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

#### 63. Create an array class that has a name attribute 

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### 82. Compute a matrix rank

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).